// Pre-Breakout Radar Data — Stocks showing tight range/volume compression BEFORE the big move
// Based on Darvas Box + SMC accumulation methodology
// Like AngelOne: was at 290 coiling, broke to 340+

export const PRE_BREAKOUT_DATA = [
  {
    id: "angelone",
    name: "Angel One Ltd",
    ticker: "ANGELONE.NS",
    sector: "Finance",
    cmp: 2810,
    w52h: 3200,
    w52l: 1800,
    compressionScore: 92,
    breakoutProbability: 88,
    signals: {
      rangeCompression: { value: "3.1%", status: "COILING", note: "5-day ATR only 3.1% — extremely tight" },
      volumeDryUp: { value: "58% of avg", status: "ACCUMULATION", note: "Volume 58% below 20-day avg — hands not selling" },
      emaConvergence: { value: "12pt spread", status: "CONVERGING", note: "EMA9/21/50 within ₹12 of each other — energy building" },
      rsiCoil: { value: "51.2", status: "NEUTRAL", note: "RSI 51.2 — perfect neutral zone, no bias = breakout ready" },
      near52H: { value: "12.2% away", status: "CLOSE", note: "Only 12% from 52W high — upper target reachable fast" },
      darvasBox: { value: "₹2,760 – ₹2,870", status: "FORMING", note: "6-week box — ceiling ₹2,870 is the breakout level" },
    },
    breakoutLevel: 2875,
    stopLoss: 2680,
    targets: [3050, 3200, 3500],
    catalysts: ["Retail demat growth 3.2M/month", "Options volume surge", "FII stake rising"],
    category: "Finance / Broking",
    holdingPeriod: "2-4 weeks",
    exampleAnalogy: "Was ₹290 → ₹340 in 2024 breakout",
    boxWeeks: 6,
    rr: 3.1,
    probScore: 8.8,
  },
  {
    id: "cdsl",
    name: "CDSL Ltd",
    ticker: "CDSL.NS",
    sector: "Finance",
    cmp: 1248,
    w52h: 1580,
    w52l: 850,
    compressionScore: 88,
    breakoutProbability: 84,
    signals: {
      rangeCompression: { value: "2.8%", status: "COILING", note: "ATR lowest in 60 days — massive contraction" },
      volumeDryUp: { value: "52% of avg", status: "ACCUMULATION", note: "Volume nearly halved from average — locked in hands" },
      emaConvergence: { value: "8pt spread", status: "CONVERGING", note: "All EMAs within ₹8 — explosion imminent" },
      rsiCoil: { value: "49.4", status: "NEUTRAL", note: "RSI 49.4 — neutral, breakout can go either way; trend says UP" },
      near52H: { value: "21% away", status: "WATCH", note: "21% from 52W high — strong runway after breakout" },
      darvasBox: { value: "₹1,200 – ₹1,285", status: "FORMING", note: "4-week box — breakout above ₹1,285 confirms" },
    },
    breakoutLevel: 1290,
    stopLoss: 1160,
    targets: [1420, 1520, 1650],
    catalysts: ["Demat account growth acceleration", "T+0 settlement benefit", "Market cap compounding"],
    category: "Depository / Capital Markets",
    holdingPeriod: "2-5 weeks",
    exampleAnalogy: "Classic low float demat monopoly — mirrors MCX 2023 base",
    boxWeeks: 4,
    rr: 2.9,
    probScore: 8.4,
  },
  {
    id: "rvnl",
    name: "Rail Vikas Nigam Ltd",
    ticker: "RVNL.NS",
    sector: "PSU",
    cmp: 298,
    w52h: 647,
    w52l: 170,
    compressionScore: 79,
    breakoutProbability: 76,
    signals: {
      rangeCompression: { value: "4.2%", status: "COILING", note: "Weekly ATR contracting for 3 consecutive weeks" },
      volumeDryUp: { value: "62% of avg", status: "ACCUMULATION", note: "Volume below average on down days — no real selling" },
      emaConvergence: { value: "18pt spread", status: "CONVERGING", note: "EMA9 approaching EMA21 — crossover due" },
      rsiCoil: { value: "46.8", status: "NEUTRAL", note: "RSI 46.8 — range bound, not oversold enough to reject" },
      near52H: { value: "Corrected 54%", status: "BASE", note: "Deep correction from 52W high — long base building" },
      darvasBox: { value: "₹280 – ₹315", status: "FORMING", note: "3-week box — needs volume spike above ₹315" },
    },
    breakoutLevel: 318,
    stopLoss: 272,
    targets: [365, 410, 480],
    catalysts: ["Railway capex ₹2.62L Cr budget", "Order book 10x in 2 years", "PSU rerating cycle"],
    category: "Railways / Infrastructure PSU",
    holdingPeriod: "3-6 weeks",
    exampleAnalogy: "Infrastructure PSU base like BEL in 2022 before 3x",
    boxWeeks: 3,
    rr: 2.6,
    probScore: 7.6,
  },
  {
    id: "suzlon",
    name: "Suzlon Energy Ltd",
    ticker: "SUZLON.NS",
    sector: "Power",
    cmp: 56.8,
    w52h: 86,
    w52l: 34,
    compressionScore: 85,
    breakoutProbability: 81,
    signals: {
      rangeCompression: { value: "3.8%", status: "COILING", note: "Lowest weekly range in 8 weeks — spring coiling" },
      volumeDryUp: { value: "55% of avg", status: "ACCUMULATION", note: "Volume drying up on dips — distribution not happening" },
      emaConvergence: { value: "₹1.2 spread", status: "CONVERGING", note: "EMA9/21 within ₹1.2 on ₹56 stock — imminent cross" },
      rsiCoil: { value: "53.1", status: "NEUTRAL", note: "RSI 53 — neutral on the long base, room to run to 70+" },
      near52H: { value: "34% away", status: "WATCH", note: "34% below 52W high — strong re-test potential" },
      darvasBox: { value: "₹54 – ₹60", status: "FORMING", note: "5-week box — strong hands accumulating at ₹54-55 level" },
    },
    breakoutLevel: 61,
    stopLoss: 51.5,
    targets: [72, 82, 95],
    catalysts: ["Renewable energy push", "Order book 3.5 GW", "Debt-free now", "Green India mission"],
    category: "Wind Energy",
    holdingPeriod: "3-6 weeks",
    exampleAnalogy: "Turnaround story — mirrors Tata Power 2020 base before 600% rally",
    boxWeeks: 5,
    rr: 3.2,
    probScore: 8.1,
  },
  {
    id: "irfc",
    name: "Indian Railway Finance Corp",
    ticker: "IRFC.NS",
    sector: "PSU",
    cmp: 174,
    w52h: 229,
    w52l: 95,
    compressionScore: 82,
    breakoutProbability: 79,
    signals: {
      rangeCompression: { value: "2.4%", status: "COILING", note: "Ultra-tight 2.4% weekly range — historically leads to strong breakouts" },
      volumeDryUp: { value: "49% of avg", status: "ACCUMULATION", note: "Volume at 49% — genuine accumulation by large hands" },
      emaConvergence: { value: "₹3 spread", status: "CONVERGING", note: "EMAs converging tightly — directional move pending" },
      rsiCoil: { value: "52.6", status: "NEUTRAL", note: "RSI 52.6 perfect base — no overhead distribution" },
      near52H: { value: "24% below", status: "BASE", note: "Strong retracement from ATH — next breakout point clear" },
      darvasBox: { value: "₹168 – ₹182", status: "FORMING", note: "6-week box — longest consolidation = more energy stored" },
    },
    breakoutLevel: 184,
    stopLoss: 162,
    targets: [210, 225, 248],
    catalysts: ["Railway electrification ₹1.08L Cr", "Dividend yield attractive", "Zero NPA rail financing"],
    category: "Railway PSU / NBFC",
    holdingPeriod: "4-8 weeks",
    exampleAnalogy: "PSU NBFC with zero-risk model — mirrors PFC 2022 before 200% run",
    boxWeeks: 6,
    rr: 2.8,
    probScore: 7.9,
  },
  {
    id: "cochinship",
    name: "Cochin Shipyard Ltd",
    ticker: "COCHINSHIP.NS",
    sector: "Defence",
    cmp: 1485,
    w52h: 2978,
    w52l: 960,
    compressionScore: 74,
    breakoutProbability: 72,
    signals: {
      rangeCompression: { value: "5.1%", status: "COILING", note: "Range contracting from prior 15% weeks — nearing base" },
      volumeDryUp: { value: "64% of avg", status: "ACCUMULATION", note: "Volume shrinking on down days — sellers exhausted" },
      emaConvergence: { value: "₹38 spread", status: "CONVERGING", note: "EMA9 curling up — momentum shift incoming" },
      rsiCoil: { value: "44.1", status: "NEUTRAL", note: "RSI 44 — near oversold recovery zone" },
      near52H: { value: "50% from ATH", status: "BASE", note: "50% from ATH — deep base = massive spring potential" },
      darvasBox: { value: "₹1,420 – ₹1,560", status: "FORMING", note: "New base forming — defence order catalysts pending" },
    },
    breakoutLevel: 1565,
    stopLoss: 1380,
    targets: [1820, 2100, 2500],
    catalysts: ["INS Vikrant follow-on orders", "Ship repair cluster", "Defence export ambitions"],
    category: "Defence Shipbuilding",
    holdingPeriod: "6-12 weeks",
    exampleAnalogy: "Defence PSU turnaround — like HAL 2023 base before doubling",
    boxWeeks: 4,
    rr: 3.5,
    probScore: 7.2,
  },
  {
    id: "zomato",
    name: "Zomato Ltd",
    ticker: "ZOMATO.NS",
    sector: "Retail",
    cmp: 238,
    w52h: 302,
    w52l: 138,
    compressionScore: 87,
    breakoutProbability: 83,
    signals: {
      rangeCompression: { value: "3.3%", status: "COILING", note: "3-week range contraction — tightest since last breakout" },
      volumeDryUp: { value: "57% of avg", status: "ACCUMULATION", note: "Volume halving — FII / institutional holding pattern" },
      emaConvergence: { value: "₹4 spread", status: "CONVERGING", note: "EMA9/21 almost touching — cross imminent" },
      rsiCoil: { value: "50.8", status: "NEUTRAL", note: "RSI 50.8 — perfect neutral launch pad" },
      near52H: { value: "21% below", status: "CLOSE", note: "21% from ATH — revisiting ATH is primary target" },
      darvasBox: { value: "₹228 – ₹250", status: "FORMING", note: "4-week box — 5th attempt at ₹250 resistance" },
    },
    breakoutLevel: 252,
    stopLoss: 218,
    targets: [278, 302, 335],
    catalysts: ["Blinkit profitability", "Q4 FY26 PAT positive", "Quick commerce TAM expansion"],
    category: "Food / Quick Commerce",
    holdingPeriod: "2-4 weeks",
    exampleAnalogy: "Digital economy breakout — similar to Nykaa 2023 base before +40%",
    boxWeeks: 4,
    rr: 3.0,
    probScore: 8.3,
  },
  {
    id: "paytm",
    name: "Paytm (One97 Comm.)",
    ticker: "PAYTM.NS",
    sector: "FinTech",
    cmp: 795,
    w52h: 998,
    w52l: 310,
    compressionScore: 80,
    breakoutProbability: 76,
    signals: {
      rangeCompression: { value: "4.4%", status: "COILING", note: "Range contracting after volatility surge — settling into box" },
      volumeDryUp: { value: "60% of avg", status: "ACCUMULATION", note: "Volume below average — post-earnings euphoria fading = new hands holding" },
      emaConvergence: { value: "₹22 spread", status: "CONVERGING", note: "EMA9 above EMA21 — uptrend intact, pullback phase" },
      rsiCoil: { value: "54.2", status: "NEUTRAL", note: "RSI 54 — bullish lean with room to accelerate" },
      near52H: { value: "20% below ATH", status: "WATCH", note: "ATH at ₹998 — if crosses ₹850, ATH retest likely fast" },
      darvasBox: { value: "₹772 – ₹840", status: "FORMING", note: "3-week box post earnings — accumulation at current levels" },
    },
    breakoutLevel: 845,
    stopLoss: 748,
    targets: [940, 998, 1120],
    catalysts: ["RBI provisional approval restored", "UPI market share regained", "Profitability inflection"],
    category: "Digital Payments / FinTech",
    holdingPeriod: "3-6 weeks",
    exampleAnalogy: "Regulatory turnaround — like Yes Bank post-RBI relief (near-term)",
    boxWeeks: 3,
    rr: 2.7,
    probScore: 7.6,
  },
];

// Nifty Options ATM Strategy Engine
// Complete strategy logic for ATM CE/PE buy or sell based on market conditions
export const NIFTY_OPTIONS_DATA = {
  // Nifty current context (May 30, 2026)
  niftySpot: 24850,
  atmStrike: 24850,
  niftyEma20: 24420,
  niftyEma50: 23980,
  niftyEma200: 22850,
  vix: 14.2,
  pcr: 0.82, // Put-Call Ratio
  prevClose: 24780,
  weeklyExpiry: "Jun 5, 2026",
  monthlyExpiry: "Jun 26, 2026",
  nearestExpiry: "Jun 5, 2026",
  
  // ATM Options premiums (approximate)
  atmCEPremium: 185,
  atmPEPremium: 155,
  
  // Market regime calculation
  marketRegime: "BULLISH_TREND",   // BULLISH_TREND | BEARISH_TREND | SIDEWAYS | HIGH_VOLATILITY
  trendStrength: "STRONG",         // STRONG | MODERATE | WEAK
  
  // Complete Strategy Recommendation
  strategies: [
    {
      id: "atm_ce_buy",
      name: "ATM Call Buy (Directional Bullish)",
      type: "BUY",
      optionType: "CE",
      strike: 24850,
      premium: 185,
      expiry: "Jun 5, 2026",
      lotSize: 25,
      costPerLot: 4625,
      maxLoss: 4625,
      target1Premium: 285,
      target2Premium: 380,
      slPremium: 115,
      profitT1: 2500,
      profitT2: 4875,
      rr: 2.3,
      probability: 72,
      idealCondition: "Nifty above 24,820 with volume. VIX < 15. PCR < 0.8",
      exitCondition: "Exit if Nifty breaks below 24,620 (structural support) or premium halves",
      bestEntry: "Between 9:15–9:45 AM on green candle open",
      avoid: "Avoid on event days (RBI, Fed). Avoid if VIX > 18",
      whySelected: "Nifty above 200 EMA, 50 EMA, 20 EMA. PCR 0.82 = bulls in control. VIX 14.2 = cheap options. Trend strong.",
      signals: ["Above 20 EMA ✅", "Above 50 EMA ✅", "VIX 14.2 cheap ✅", "PCR 0.82 bullish ✅", "Price > prev week high ✅"],
    },
    {
      id: "atm_pe_sell",
      name: "ATM Put Sell (Theta Decay Bullish)",
      type: "SELL",
      optionType: "PE",
      strike: 24850,
      premium: 155,
      expiry: "Jun 5, 2026",
      lotSize: 25,
      costPerLot: 0,
      maxLoss: "Unlimited (Hedge with OTM PE buy)",
      maxProfit: 3875,
      slPremium: 310, // Exit if PE doubles
      target1Premium: 80,
      target2Premium: 30,
      profitT1: 1875,
      profitT2: 3125,
      rr: 2.0,
      probability: 68,
      idealCondition: "Nifty holding 24,700 support. VIX declining. Sell on rise in PE premium",
      exitCondition: "Buy back if PE premium > ₹310 (double). Exit if Nifty < 24,600 on close",
      bestEntry: "Sell PE between 10–11 AM when premium peaks due to volatility",
      avoid: "Do NOT sell PE if VIX > 17 or any major event within 2 days",
      whySelected: "Strong trend means OTM puts decay fast. Theta works in your favour over next 6 days.",
      signals: ["Strong uptrend", "VIX moderate", "Time decay accelerating", "Support holding"],
    },
    {
      id: "bull_call_spread",
      name: "Bull Call Spread (Low-Cost Bullish)",
      type: "SPREAD",
      optionType: "CE",
      buyStrike: 24850,
      sellStrike: 25100,
      buyPremium: 185,
      sellPremium: 78,
      netCost: 107,
      maxLoss: 2675, // per lot
      maxProfit: 3575, // per lot
      breakeven: 24957,
      expiry: "Jun 5, 2026",
      lotSize: 25,
      rr: 1.34,
      probability: 74,
      idealCondition: "Nifty expected to move to 25,100 before Jun 5. Use when VIX is low (cheap premiums)",
      exitCondition: "Exit full spread if Nifty loses 24,750. Take 70% profit at ₹24,980",
      bestEntry: "Enter on dip to 24,800–24,820 for lower cost",
      avoid: "Avoid if move expected > 300 pts — CE buy alone better",
      whySelected: "Reduces cost by 42% vs pure CE buy. Ideal for steady trending market with limited volatility.",
      signals: ["Low VIX (14.2)", "Defined risk", "Reduced theta exposure", "Bullish bias confirmed"],
    },
  ],
  
  // Market analysis summary
  marketAnalysis: {
    trendStatus: "BULLISH",
    niftyVsEmas: {
      above200: true,
      above50: true,
      above20: true,
      note: "Nifty above all key EMAs — classic trending bull market structure"
    },
    vixAnalysis: {
      current: 14.2,
      regime: "LOW",
      recommendation: "BUY options (cheap premiums)",
      note: "VIX 14.2 is low — great time to BUY options. Avoid selling naked options in this regime."
    },
    pcrAnalysis: {
      current: 0.82,
      interpretation: "BULLISH",
      note: "PCR 0.82 — more call buyers = market expects upside. No extreme fear/greed."
    },
    thetaDecayAdvice: "Expiry on Jun 5 (6 days away) — theta decay accelerating. Buyers must target 50%+ premium move within 3 days or exit.",
    supportResistance: {
      keySupport: [24620, 24420, 24180],
      keyResistance: [25000, 25250, 25500],
      criticalLevel: 24620,
      note: "Critical support 24,620 (previous swing high). Must hold for bullish thesis."
    }
  },
  
  // Nifty ATM Options Rules (Complete Strategy Framework)
  rules: [
    { rule: "Buy CE when Nifty > 20 EMA + 50 EMA + 200 EMA (triple confirmation)", type: "ENTRY_RULE" },
    { rule: "Buy PE when Nifty < 20 EMA AND breaking weekly support with volume", type: "ENTRY_RULE" },
    { rule: "Never buy options when VIX > 22 (IV crush risk post-event)", type: "VIX_RULE" },
    { rule: "Prefer selling options when VIX > 18 (high premium income)", type: "VIX_RULE" },
    { rule: "Buy ATM options only — not OTM (probability too low)", type: "STRIKE_RULE" },
    { rule: "Exit CE/PE at 50% loss — no averaging on options", type: "SL_RULE" },
    { rule: "Book 50% profit at T1, trail rest with premium SL", type: "PROFIT_RULE" },
    { rule: "Avoid option buying on Monday (weekend decay) + expiry day (gamma risk)", type: "TIMING_RULE" },
    { rule: "PCR < 0.7 = extreme bullishness → book CE, consider PE", type: "PCR_RULE" },
    { rule: "PCR > 1.3 = extreme fear → book PE, consider CE", type: "PCR_RULE" },
    { rule: "Best option buying days: Tuesday, Wednesday (peak theta exposure to expiry)", type: "TIMING_RULE" },
  ]
};
